### ISSUE TITLE
Missing product-variation-attributes.php template

### ISSUE THREAD

**Issue by helgatheviking** [seb86/WooCommerce-Match-Box#1]
>Notice: wc_get_template was called <strong>incorrectly</strong>. <code>D:\Websites\www.sandbox.dev\wp-content\plugins\WooCommerce-Match-Box/templates/single-product/item/product-variation-attributes.php</code> does not exist. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 2.1.) in D:\Websites\www.sandbox.dev\wp-includes\functions.php on line 3897

Relatedly, it looks like you are overriding templates but not doing anything different, like the short description template, title, thumbnail, etc. If there's no modification, it's probably best to attach my original template to your new location.

**Comment by seb86** [comment]
@helgatheviking Opps. I must have forgotten about that one. The client was only working with simple products. I will look into using your templates instead.

**Comment by helgatheviking** [comment]
Will be closed by 771a634122086a059daf2392f8b4da7146715590
