### ISSUE TITLE
Images are displaying Icon Size

### ISSUE THREAD

**Issue by fizzyfanatics** [seb86/WooCommerce-Match-Box#17]
Hi i love the plugin but the issue i have with it is the product image is small when displaying the images on mix and match. They don't display like the shown on the demo images on here. They currently displaying as thumbnail size which mean people wouldn't be able to see the products available in the store to select.

I'm using the woo commerce storefront theme

**Comment by fizzyfanatics** [comment]
here a link to see what i mean

http://prntscr.com/coz0cm

**Comment by seb86** [comment]
This is to do with the product image sizes under `WooCommerce -> Settings`. You will need to adjust the size you want for the product thumbnail and then regenerate the images using [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) plugin.

**Comment by fizzyfanatics** [comment]
sadly done what youve said and it not made any difference what so ever was so hoping to use this plugin

**Comment by seb86** [comment]
The images need to be larger than the image it generates so I don't see why this should not be working. As you can see from the screenshots I have shown in the README.md file it displays fine on the theme Storefront but only if the images were large to begin with.
