### ISSUE TITLE
Twenty Sixteen support

### ISSUE THREAD

**Issue by helgatheviking** [seb86/WooCommerce-Match-Box#2]
I tried your mini extension with Twenty Sixteen and this is what I get:

![image](https://cloud.githubusercontent.com/assets/507025/16659022/816243ee-4436-11e6-874c-b7fe26a649b5.png)

**Comment by seb86** [comment]
@helgatheviking Oh dear. I guess the theme has other WooCommerce overrides. I will look into that.

**Comment by helgatheviking** [comment]
I think I included this in https://github.com/seb86/WooCommerce-Match-Box/pull/6/commits/79f419f3bbee4cad7d604b600a1008d25a6aa22a

**Comment by seb86** [comment]
Fixed in commit a67f7150d2c5e94dd247f279338791b1e2ecff93
