### ISSUE TITLE
Duplicate form elements

### ISSUE THREAD

**Issue by helgatheviking** [seb86/WooCommerce-Match-Box#3]
In the markup I see 2 `<form>` elements. It appears that you are relying on JS to hide the original. Instead, I think it would be best to override the `add-to-cart/mnm.php` and `mnm/mnm-item.php` templates to switch them from table to div markup.

**Comment by seb86** [comment]
@helgatheviking Yes, I had a trouble removing your _add-to-cart_ template so I decided to hide it for now. [Removing it](https://github.com/seb86/WooCommerce-Match-Box/blob/master/includes/class-wcmb-template.php#L89) does not seem to work and I tried many combinations. It's possible it is protected in your extension.

**Comment by helgatheviking** [comment]
Two things, your template class is called on `woocommerce_init` so it might already be too late, I'm not sure. But secondly, you need

`remove_action( 'woocommerce_mix-and-match_add_to_cart', array( WC_Mix_and_Match()->display, 'add_to_cart_template' ) );`

I'm tinkering around, may have a PR, though I'm trying not to get too sucked in.

**Comment by helgatheviking** [comment]
Will be closed by https://github.com/seb86/WooCommerce-Match-Box/pull/6/commits/477711f61378ff0a33079b3b3f689a35fcc108ea

**Comment by seb86** [comment]
@helgatheviking Still appears to be loading the original template.

**Comment by seb86** [comment]
Fixed in this commit 2aaceb109670b1eaf7ccf1521548d739c331dc5e.
