### ISSUE TITLE
Don't duplicate add-to-cart-mnm.js, use triggers

### ISSUE THREAD

**Issue by helgatheviking** [seb86/WooCommerce-Match-Box#4]
By duplicating the script you'll always have to modify it if ever the core MNM plugin changes. By using triggers you'll stay up to date with less work.

**Comment by seb86** [comment]
@helgatheviking Yes. I am aware of that. This extension was built for a client originally so I was trying to save time with the budget I was given. I want to use triggers instead but I don't have the time to do that just now.

You are welcome to contribute changes you see fit to make it better.

**Comment by helgatheviking** [comment]
Will be closed by 182c06478e63ffd0968da5086381c016320275f2
