### ISSUE TITLE
Remove or move sale badge

### ISSUE THREAD

**Issue by helgatheviking** [seb86/WooCommerce-Match-Box#5]
Without the main product image the sale badge is weirdly positioned:

![image](https://cloud.githubusercontent.com/assets/507025/16661671/09ab1a2c-4442-11e6-85f6-e9a5bc334053.png)

**Comment by seb86** [comment]
@helgatheviking Is it important to be at the top with the product title?

**Comment by helgatheviking** [comment]
Not necessarily, but it should be towards the top because it should be visible. Normally it is right on top of the corner of the product image.

**Comment by seb86** [comment]
OK, so perhaps moving the title along to the right of the sale badge would be OK.

**Comment by helgatheviking** [comment]
That might work.

**Comment by seb86** [comment]
Made the change in these two commits. b1e147023e90cca972fc2d20696431da50f5586f and 3ad5157dd005b28127fa55e543c3b56fd1cb4741
